# Generated by Django 3.2 on 2021-04-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='text',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
