# Generated by Django 3.2 on 2021-04-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('news_site', '0002_customuser_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='task',
            field=models.ManyToManyField(to='django_celery_beat.PeriodicTask'),
        ),
    ]
