# Generated by Django 3.2 on 2021-04-26 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0004_urls_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Urls_table',
            new_name='UrlsTable',
        ),
    ]
