# Generated by Django 3.2 on 2021-04-26 19:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0005_rename_urls_table_urlstable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlstable',
            name='customuser',
        ),
        migrations.AddField(
            model_name='urlstable',
            name='customuser',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
