# Generated by Django 3.2 on 2021-04-26 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0006_auto_20210426_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlstable',
            name='customuser',
        ),
        migrations.AddField(
            model_name='customuser',
            name='urls',
            field=models.ManyToManyField(to='news_site.UrlsTable'),
        ),
    ]
