# Generated by Django 3.2 on 2021-04-27 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0007_auto_20210426_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prior', models.IntegerField(blank=True, null=True)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_site.urlstable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
