# Generated by Django 3.2 on 2021-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0008_priorityforuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='urls',
            field=models.ManyToManyField(through='news_site.PriorityForUser', to='news_site.UrlsTable'),
        ),
    ]
