# Generated by Django 3.2 on 2021-04-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0009_alter_customuser_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='task',
        ),
    ]
