# Generated by Django 3.2 on 2021-05-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0012_urlstable_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='site_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news_site.urlstable'),
        ),
        migrations.AlterField(
            model_name='urlstable',
            name='site_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='urlstable',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
