# Generated by Django 3.2 on 2021-05-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0014_samenews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['news_text']},
        ),
        migrations.AddField(
            model_name='news',
            name='same_news',
            field=models.ManyToManyField(related_name='_news_site_news_same_news_+', to='news_site.News', verbose_name='Same News'),
        ),
        migrations.DeleteModel(
            name='SameNews',
        ),
    ]
