# Generated by Django 3.2.1 on 2021-05-04 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0023_alter_news_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-pub_date']},
        ),
        migrations.CreateModel(
            name='CategoryForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_site.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='categories',
            field=models.ManyToManyField(through='news_site.CategoryForUser', to='news_site.Category'),
        ),
    ]
