# Generated by Django 3.2.1 on 2021-05-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0026_auto_20210504_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsforcategory',
            name='prior',
            field=models.IntegerField(blank=True, default=999, null=True),
        ),
    ]
