# Generated by Django 3.2.1 on 2021-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0027_alter_urlsforcategory_prior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={},
        ),
        migrations.AlterModelOptions(
            name='urlsforcategory',
            options={'ordering': ['prior']},
        ),
        migrations.AddField(
            model_name='news',
            name='user_tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
