# Generated by Django 3.2.1 on 2021-05-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_site', '0029_remove_news_user_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_tags',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
